backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Articles"
    name: "article"
    folder: "src/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date", format: "MMMM Do YYYY" }
      - { label: "Body", name: "body", widget: "markdown"}
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "created", "from", "config.yml"]

  - label: "Commercial Services"
    name: "commercial-services"
    folder: "src/services/commercial-services"
    slug: "{{title}}"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Service Images", name: "service-images", widget: "image", media_folder: "src/services/commercial-services/images"}
      - { label: "Body", name: "body", widget: "markdown"}
  
  - label: "Residential Services"
    name: "reisdential-services"
    folder: "src/services/residential-services"
    create: true
    fields:
        - { label: "Service Name", name: "service_name", widget: "string" }
        - { label: "Service Images", name: "service_images", widget: "image", media_folder: "src/services/residential-services/images"}
        - { label: "Service Description", name: "service_description", widget: "markdown"}
          

  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Quick Links"
        name: "links"
        file: "src/_data/quicklinks.yaml"
        fields:
          - label: Nav Items
            name: links
            widget: list
            collapsed: false
            fields:
              - { label: Title, name: title, widget: string }
              - { label: URL, name: url, widget: string }
              - { label: Description, name: desc, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }

  - label: "All Widgets"
    name: "allWidgets"
    files:
      - label: "Blog Post Hero Image"
        name: "blogPostHeroImage"
        widget: "list"
        file: "src/_data/settings.yaml"
        fields: 
          - label: Hero Image
            name: heroImage
            widget: object
            minimized_collapsed: true
            allow_add: true
            collapsed: true
            fields:
              - {label: Hero Image, name: image, widget: image}
              - { label: Image Title, name: title, widget: string}
          - label: Post Title
            name: postTitle
            widget: string
          

        